name: Build Aermos APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Aermos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.2'

      - name: Build Debug APK
        run: gradle assembleDebug --stacktrace

      - name: Upload Aermos APK
        uses: actions/upload-artifact@v4
        with:
          name: Aermos-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error